---
version: "3"

vars:
  PYTHON_BIN: python3
  ANSIBLE_DIR: "{{.ROOT_DIR}}/ansible"

env:
  PATH: "{{.ROOT_DIR}}/.venv/bin:$PATH"
  VIRTUAL_ENV: "{{.ROOT_DIR}}/.venv"
  ANSIBLE_COLLECTIONS_PATH: "{{.ROOT_DIR}}/.venv/galaxy"
  ANSIBLE_ROLES_PATH: "{{.ROOT_DIR}}/.venv/galaxy/ansible_roles:{{.ROOT_DIR}}/ansible/roles"
  ANSIBLE_VARS_ENABLED: "host_group_vars,community.sops.sops"

includes:
  profile: .taskfiles/ProfileTacks.yaml
  editor: .taskfiles/EditorTasks.yaml

tasks:

  default: task -l

  deps:
    desc: Create a Python virtual env and install required packages
    summary: task {{.TASK}}
    cmds:
      - "{{.PYTHON_BIN}} -m venv {{.ROOT_DIR}}/.venv"
      - .venv/bin/python3 -m pip install --upgrade pip setuptools wheel
      - .venv/bin/python3 -m pip install --upgrade --requirement "{{.ROOT_DIR}}/requirements.txt"
      - .venv/bin/ansible-galaxy install --role-file "{{.ROOT_DIR}}/requirements.yaml" --force