---
- name: Create working directories
  file:
    path: "/home/{{ ansible_user }}/src/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:
    - tools
    - data
    - github.com